<?php

return [

    'menu' => [
        'home' => 'HOME',
        'about' => 'ABOUT',
        'service' => 'SERVICES',
        'docteur' => 'DOCTORS',
        'convention' => 'CONVENSIONS',
        'contact' => 'CONTACT',
        'langue' => 'LANGUAGE',
        'rdv' => 'APPOINTMENT',
    ],
    'home' => [
        'slide' => 'Take The world’s Best Quality Medical Treatmen for',
        'slideDesciprion' => 'The quality of our service and the professionalism of our staff are the reason for Trustlife Center’s success',
        'slideBtVideo' => 'Watch The Video',
        't1' => 'Qualified Doctors',
        'desc1' => 'Our doctors have a wide range of clinical experience ranging from newly qualified junior doctors to senior consultants.',
        't2' => 'Emergency Care',
        'desc2' => 'Our centers provide convenient and high-quality care for a variety of common illnesses and injuries.',
        't3' => '24 Hours Service',
        'desc3' => 'Our technical team is available for 24/7, We always prepared any emergency situation with 10 ambulances.',
    ],
    'about' => [
        'titre' => 'Who we are',
        't1' => 'Why People Choose Our Hospital?',
        'desc1' => 'Watch The Video',
        'bt' => 'Read more',
        'heureOuv' => 'Opening Hours',
        'HeureVisite' => 'Visitors Hours',
        'desc2' => 'Our centers provide convenient and high-quality care for a variety of common illnesses and injuries.',
        't3' => '24 Hours Service',
        'desc3' => 'Our technical team is available for 24/7, We always prepared any emergency situation with 10 ambulances.',
    ],
    'convension' => [
        'slide' => 'Take The world’s Best Quality Medical Treatmen for',
        'slideDesciprion' => 'The quality of our service and the professionalism of our staff are the reason for Trustlife Center’s success',
        'slideBtVideo' => 'Watch The Video',
        't1' => 'Qualified Doctors',
        'desc1' => 'Our doctors have a wide range of clinical experience ranging from newly qualified junior doctors to senior consultants.',
        't2' => 'Emergency Care',
        'desc2' => 'Our centers provide convenient and high-quality care for a variety of common illnesses and injuries.',
        't3' => '24 Hours Service',
        'desc3' => 'Our technical team is available for 24/7, We always prepared any emergency situation with 10 ambulances.',
    ],
    'contact' => [
        'slide' => 'Take The world’s Best Quality Medical Treatmen for',
        'slideDesciprion' => 'The quality of our service and the professionalism of our staff are the reason for Trustlife Center’s success',
        'slideBtVideo' => 'Watch The Video',
        't1' => 'Qualified Doctors',
        'desc1' => 'Our doctors have a wide range of clinical experience ranging from newly qualified junior doctors to senior consultants.',
        't2' => 'Emergency Care',
        'desc2' => 'Our centers provide convenient and high-quality care for a variety of common illnesses and injuries.',
        't3' => '24 Hours Service',
        'desc3' => 'Our technical team is available for 24/7, We always prepared any emergency situation with 10 ambulances.',
    ],
    'departement' => [
        'slide' => 'Take The world’s Best Quality Medical Treatmen for',
        'slideDesciprion' => 'The quality of our service and the professionalism of our staff are the reason for Trustlife Center’s success',
        'slideBtVideo' => 'Watch The Video',
        't1' => 'Qualified Doctors',
        'desc1' => 'Our doctors have a wide range of clinical experience ranging from newly qualified junior doctors to senior consultants.',
        't2' => 'Emergency Care',
        'desc2' => 'Our centers provide convenient and high-quality care for a variety of common illnesses and injuries.',
        't3' => '24 Hours Service',
        'desc3' => 'Our technical team is available for 24/7, We always prepared any emergency situation with 10 ambulances.',
    ],
    'medecin' => [
        'slide' => 'Take The world’s Best Quality Medical Treatmen for',
        'slideDesciprion' => 'The quality of our service and the professionalism of our staff are the reason for Trustlife Center’s success',
        'slideBtVideo' => 'Watch The Video',
        't1' => 'Qualified Doctors',
        'desc1' => 'Our doctors have a wide range of clinical experience ranging from newly qualified junior doctors to senior consultants.',
        't2' => 'Emergency Care',
        'desc2' => 'Our centers provide convenient and high-quality care for a variety of common illnesses and injuries.',
        't3' => '24 Hours Service',
        'desc3' => 'Our technical team is available for 24/7, We always prepared any emergency situation with 10 ambulances.',
    ],
];
